### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by KishriA** [friendlyanon/decensooru#1]
I have BBB v8.2 installed (chrome-tampermonkey) and it seems to be functioning correctly. Making sure to check the correct boxes in the setting I attempted to use this. Everything was going right until the small window opened up downloading batch #0. After a few minutes it would close and nothing seemed to have happened. Any thoughts?

Also it would repeat this after a few minutes giving the notification in the corner to download, and again only be downloading batch #0 until it would close. Repeating the cycle. I also have all my adblock stuff disabled if that helps.

**Comment by friendlyanon** [comment]
I cleared my IndexedDB storage and tried the initial setup, which finished with 0 issues and all the restricted content was visible.
You're on your own with this, I'm afraid. Make sure you followed every instruction precisely from the readme.

**Comment by friendlyanon** [comment]
Version 0.9.2.0 was released and as seen in [the video from README](https://streamable.com/utqxa), it installs properly in Chrome, but due to some issues `IndexedDB` is very slow when adding lots of new data. `IndexedDB` related issues are being looked at by Google, so I can't really do anything about this. I made the progress display better in the popup so you can see it doing its thing in case you were wondering if it worked at all.
