### ISSUE TITLE
Couldn't load some images

### ISSUE THREAD

**Issue by S4WA** [friendlyanon/decensooru#5]
I can't see [this](https://danbooru.donmai.us/posts/2792416) and [this](danbooru.donmai.us/posts/3780706)

first post have 404 error. but it can see from thumbnail.
![image](https://user-images.githubusercontent.com/24929259/77718734-f46be000-7026-11ea-8142-3e984de3d2e6.png)

and second post says it isn't in database.
![image](https://user-images.githubusercontent.com/24929259/77718833-2ed57d00-7027-11ea-9a65-047cc7bbadc7.png)

and BBB says ``Error checking account settings (HTML Code: 404 ).``
![image](https://user-images.githubusercontent.com/24929259/77718633-c7b7c880-7026-11ea-9c4f-5d02bffbdc7c.png)

**Comment by Vladimir1010** [comment]
Danbooru changed something in their servers which changed how hidden tags show now. The creator of the extension is in need of a new gold or higher account API key in order to update the extension. If you do know someone who holds a gold or higher account, you can direct them here to help with the extension, unless you have your own gold and higher account.

**Comment by S4WA** [comment]
I see.
